services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    env_file:
      - .env
    volumes:
      - ollama_data:/root/.ollama
      - ./docker/ollama/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    restart: unless-stopped

  mcp-server:
    build: .
    container_name: mcp-server
    ports:
      - "8081:8081"
    volumes:
      - ./:/app/config   # mapeia a pasta host config
    env_file:
      - .env
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data: